FROM python:3.9-slim

WORKDIR /app

COPY . /app
COPY file_monitor_pb2.py .
COPY file_monitor_pb2_grpc.py .
COPY recovery_client.py .

RUN pip install --no-cache-dir grpcio grpcio-tools kafka-python

CMD ["python", "KafkaConsumer.py"]
